### ISSUE TITLE
Print a warning about shell glob expansion if too many arguments are given

### ISSUE THREAD

**Issue by camjackson** [c4milo/github-release#1]
If someone (like me) is silly and doesn't escape or quote their file glob pattern, then the shell will expand it, resulting in a command like:

``` shell
github-release name/repo tag master "New release!" some_dir/file1 some_dir/file2
```

Currently, the first file is treated as the only file, and extra file parameters are just ignored. Given that the files parameter is the last one, it would be nice if this tool would detect the extra parameters and warn that your shell might be expanding the glob.

Alternately, perhaps the tool could support a list of files, rather than just a single glob? That way the shell expansion wouldn't be an issue.

**Comment by c4milo** [comment]
@camjackson I've made the clarification in the usage: https://github.com/c4milo/github-release/blob/master/main.go#L64 and https://github.com/c4milo/github-release/blob/master/main.go#L72

**Comment by camjackson** [comment]
Looks good. I've opened #2 to add the same change to the readme.
